apiVersion: v1
kind: Service
metadata:
  name: nginx-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}{{ if .Values.nginx.service.annotations }}
    {{ range $key, $value := .Values.nginx.service.annotations }}{{ $key }}: {{ $value | quote }}{{ end }}{{ end }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: nginx
spec:
  type: {{ .Values.nginx.service.type }}
  ipFamilyPolicy: {{ .Values.nginx.service.ipFamilyPolicy }}
  ports:
    - port: {{ .Values.nginx.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: nginx-{{ .Release.Name }}
