apiVersion: v1
kind: Service
metadata:
  name: astro-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}{{ if .Values.astro.service.annotations }}
    {{ range $key, $value := .Values.astro.service.annotations }}{{ $key }}: {{ $value | quote }}{{ end }}{{ end }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: astro
spec:
  type: {{ .Values.astro.service.type }}
  ipFamilyPolicy: {{ .Values.astro.service.ipFamilyPolicy }}
  ports: {{ if .Values.astro.ssh.enabled }}
    - port: 22
      targetPort: 22
      protocol: TCP
      name: ssh {{ end }}
    - port: {{ .Values.astro.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http-alt 
  selector:
    app: astro-{{ .Release.Name }}
